"""empty message

Revision ID: 069fcba38669
Revises: 92aae63a19ff
Create Date: 2023-06-01 19:12:05.842493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069fcba38669'
down_revision = '92aae63a19ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers_followed',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers_followed')
    # ### end Alembic commands ###
